# Generated by Django 4.1.13 on 2024-04-09 04:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0002_rename_journalprofile_journal_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Journal",
            new_name="JournalProfile",
        ),
        migrations.RenameIndex(
            model_name="journalprofile",
            new_name="journal_jou_ranking_d32394_idx",
            old_name="journal_jou_ranking_4d6d82_idx",
        ),
    ]
